### ISSUE TITLE
 Some questions.

### ISSUE THREAD

**Issue by Haifeng3** [weilllllls/OnPro#1]
Great work! I have a few questions that I hope the authors can address: 1) Why do you perform Online Prototype Equilibrium separately in $X$ and $X^b$ instead of directly conducting it on all samples in $X \cup X^b$? Wouldn't the latter be more effective in preventing shortcut learning when there are more seen classes? 2) After filtering samples through APF and performing Mixup, then using them as samples in $X^b$ , how do you calculate the prototype $\mathbf{p}_i^b$ ​of the Mixup sample class during Online Prototype Equilibrium?

**Comment by weilllllls** [comment]
Thank you for your interest in our work. (1) $X \cup X^b$ may not include more classes compared to $X^b$ since $X^b$ already contains samples from the incoming (new) classes. Conducting OPE on $X \cup X^b$ may suffer from the class imbalance issue. (2) We apologize for any confusion. Mixup samples are not used in the OPE process. You can find additional details in the provided code.

**Comment by Haifeng3** [comment]
Thanks for your helpful response!
